export const products = [
    {
        id: 'beginners-sketching',
        name: "Beginner's Sketching Course",
        description: "Master the fundamentals of fashion illustration and bring your ideas to life on paper.",
        price: 199,
        priceFormatted: "$199",
        imageUrl: "/Beginner's Sketching Course.jpg",
        imageHint: "fashion sketch",
        isFeatured: true,
    },
    {
        id: 'advanced-pattern',
        name: "Advanced Pattern Making",
        description: "Learn to create complex patterns for bespoke garments with our in-depth, hands-on course.",
        price: 349,
        priceFormatted: "$349",
        imageUrl: "/Advanced Pattern Making.jpg",
        imageHint: "sewing pattern",
        isFeatured: true,
    },
    {
        id: 'digital-design',
        name: "Digital Fashion Design 101",
        description: "Step into the future of fashion. Learn to design and render using industry-standard software.",
        price: 299,
        priceFormatted: "$299",
        imageUrl: "/Digital Fashion Design 101.jpg",
        imageHint: "digital design",
        isFeatured: true,
    },
    {
        id: 'sewing-masterclass',
        name: "Complete Sewing Masterclass",
        description: "From basic stitches to complex garment construction, this course covers everything.",
        price: 499,
        priceFormatted: "$499",
        imageUrl: "/Complete-Sewing-Masterclass.png",
        imageHint: "sewing machine fabric",
        isFeatured: false,
    },
    {
        id: 'fashion-history',
        name: "History of Fashion",
        description: "Explore the evolution of style and learn from the masters of the past to inform your designs.",
        price: 149,
        priceFormatted: "$149",
        imageUrl: "/History of Fashion.jpg",
        imageHint: "vintage fashion books",
        isFeatured: false,
    },
    {
        id: 'mentorship',
        name: "Personal Mentorship Package",
        description: "One-on-one guidance to develop your unique collection and brand identity.",
        price: 799,
        priceFormatted: "$799",
        imageUrl: "/Personal Mentorship Package.jpg",
        imageHint: "fashion designer meeting",
        isFeatured: false,
    },
];
